{% set version = "1.5.24" %}

package:
  name: python-blockbuster
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/blockbuster/blockbuster-{{ version }}.tar.gz
  sha256: 97645775761a5d425666ec0bc99629b65c7eccdc2f770d2439850682567af4ec

build:
  number: 0
  skip: True  # [py<38]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling
    - pip
    - python
  run:
    - forbiddenfruit >=0.1.4
    - python

test:
  source_files:
    - tests/
    - pyproject.toml
  imports:
    - blockbuster
  requires:
    - pip
    - pytest-asyncio
    - pytest-cov
    - requests
  commands:
    - pip check
    - coverage run --source=blockbuster --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=89

about:
  homepage: https://github.com/cbornet/blockbuster
  license: Apache-2.0
  license_file: LICENSE
  summary: Utility to detect blocking calls in the async event loop

extra:
  recipe-maintainers:
    - bollwyvl